src/home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('' , home , name="home" ),
]

src/project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('inventory/', include('inventory.urls')),
    path('transaction/', include('transaction.urls')),
    path('', include('home.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/transaction/urls.py
from django.urls import path 
from .views import *



urlpatterns = [
    path('supliers_list' , SuplierListView.as_view() , name='supliers_list'),
    path('create_suplier' , CreateSuplierView.as_view() , name='create_suplier'),
    path('update_suplier/<str:pk>',UpdateSuplierView.as_view(),name='update_suplier'),
    path('delete_suplier/<str:pk>',DeleteSuplierView.as_view(),name='delete_suplier'),
    path('supplier_details/<str:pk>',SupplierDetailsView.as_view(),name='supplier_details'),

    #Purchases

    path('purchase_list' , PurchseListView.as_view() , name='purchase_list' ),
    path('select_supplier', SelectSupplierView.as_view(), name='select_supplier'),
    path('new_purchase/<str:pk>',PurchaseCeateView.as_view(), name='new_purchase'),
    path('purchase_delete/<str:pk>',PurchaseDeleteView.as_view(), name='delete_purchase'),
    path('purchase_bill/<str:bill_no>', PurchaseBillView.as_view(), name='purchase_bill'),

    #Sales
    path('sales/list' , SaleBill.as_view() , name='sales_list'),
    path('sales/create' , SaleCreateView , name='sale_craete'),
    path('sales/delete/<str:pk>' , SaleDeleteView.as_view(), name='sale_delete'),
    path('sales/<bill_no>' , SaleBillView.as_view() , name='sale_bill'),


]

src/transaction/models.py
from django.db import models
import uuid
from inventory.models import InventoryStock

class Supplier(models.Model):
    id = models.UUIDField(primary_key=True , default=uuid.uuid4)
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=12 , unique=True)
    address = models.CharField(max_length=200)
    email = models.EmailField(max_length=200 , unique=True)
    gstin = models.CharField(max_length=15 , unique=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name




class PurchaseItem(models.Model):
    bill_no = models.ForeignKey("PurchaseBill" , on_delete=models.CASCADE , related_name="purchase_bill")
    stock = models.ForeignKey(InventoryStock , on_delete=models.CASCADE , related_name="purchase_stock")
    quantity = models.IntegerField(default=1)
    per_price = models.IntegerField(default=1)
    total_price = models.IntegerField(default=1)


    def __str__(self):
        return "Bill no " + str(self.bill_no.bill_no) + "item = " + self.stock.name
    

class PurchaseBill(models.Model):
    bill_no = models.UUIDField(primary_key=True , default=uuid.uuid4)
    time = models.DateTimeField(auto_now_add=True)
    suplier = models.ForeignKey(Supplier , on_delete=models.CASCADE , related_name="purchaseBill")

    def __str__(self):
        return "Bill no " + str(self.bill_no)

    def get_total_price(self):
        purchaseItems = PurchaseItem.objects.filter(bill_no=self)
        total = 0
        for item in purchaseItems:
            total += item.total_price
        return total
    def get_items_list(self):
        return PurchaseItem.objects.filter(bill_no = self)
    
class PurchaseBillDetails(models.Model):
    bill_no = models.ForeignKey(PurchaseBill , on_delete=models.CASCADE ,related_name="purchaseBillDetail")
    eway = models.CharField(max_length=50 , blank=True , null=True )
    veh = models.CharField(max_length=50 , blank=True , null=True )
    destination = models.CharField(max_length=50 , blank=True , null=True )
    po = models.CharField(max_length=50 , blank=True , null=True )

    cgst = models.CharField(max_length=50 , blank=True , null=True )
    sgst = models.CharField(max_length=50 , blank=True , null=True )
    igst = models.CharField(max_length=50 , blank=True , null=True )
    cess = models.CharField(max_length=50 , blank=True , null=True )
    tcs = models.CharField(max_length=50 , blank=True , null=True )

    total = models.CharField(max_length=50 , blank=True , null=True )

    def __str__(self):
        return "Bill No " + str(self.bill_no.bill_no)
    

# Sale Section

class SaleBill(models.Model):
    bill_no = models.UUIDField(primary_key=True , default=uuid.uuid4)
    time = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=12 , unique=True)
    address = models.CharField(max_length=200)
    email = models.EmailField(max_length=200 , unique=True)
    gstin = models.CharField(max_length=15 , unique=True)

    def __str__(self):
        return "Sale Bill No " + str(self.bill_no)
    
    def get_total_price(self):
        saleItems = SaleItem.objects.filter(bill_no=self)
        total = 0
        for item in saleItems:
            total += item.total_price
        return total
    def get_items_list(self):
        return SaleItem.objects.filter(bill_no = self)
    
class SaleItem(models.Model):
     bill_no = models.ForeignKey(SaleBill , on_delete=models.CASCADE , related_name="sale_bill")
     stock = models.ForeignKey(InventoryStock , on_delete=models.CASCADE , related_name="sale_stock")
     quantity = models.IntegerField(default=1)
     per_price = models.IntegerField(default=1)
     total_price = models.IntegerField(default=1)

     def __str__(self):
        return " Sale Bill no " + str(self.bill_no.bill_no) + "item = " + self.stock.name


class SaleBillDetail(models.Model):
    bill_no = models.ForeignKey(SaleBill , on_delete=models.CASCADE ,related_name="saleBillDetail")
    eway = models.CharField(max_length=50 , blank=True , null=True )
    veh = models.CharField(max_length=50 , blank=True , null=True )
    destination = models.CharField(max_length=50 , blank=True , null=True )
    po = models.CharField(max_length=50 , blank=True , null=True )

    cgst = models.CharField(max_length=50 , blank=True , null=True )
    sgst = models.CharField(max_length=50 , blank=True , null=True )
    igst = models.CharField(max_length=50 , blank=True , null=True )
    cess = models.CharField(max_length=50 , blank=True , null=True )
    tcs = models.CharField(max_length=50 , blank=True , null=True )

    total = models.CharField(max_length=50 , blank=True , null=True )

    def __str__(self):
        return "Sale Details Bill No " + str(self.bill_no.bill_no)

src/transaction/views.py
from django.shortcuts import render , redirect , get_object_or_404
from .forms import *
from .models import *
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.views import generic
from django.core.paginator import Paginator


class SuplierListView(generic.ListView):
    queryset = Supplier.objects.filter(is_deleted=False)
    template_name = "suplier/list_supliers.html"
    paginate_by = 10

class SupplierDetailsView(generic.DetailView):
    model = Supplier
    template_name = 'suplier/supplier_details.html'
    context_object_name = 'supplier'

    def get_context_data(self , **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Get all purchase bills for this supplier
        purchase_bills = self.object.purchaseBill.all()
        
        # Add pagination (show 10 bills per page)
        paginator = Paginator(purchase_bills, 1)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context['page_obj'] = page_obj
        return context
    # def get(self , request , name):
    #     sup_obj = get_object_or_404(Supplier , name=name)
    #     bill_list = PurchaseBill.objects.filter(suplier=sup_obj)
    #     page = request.GET.get('page' , 1)
    #     paginator = Paginator(bill_list , 1)
    #     try:
    #         bills = paginator.page(page)
    #     except PageNotAnInteger:
    #         bills = paginator.page(1)
    #     except EmptyPage:
    #         bills = paginator.page(paginator.num_pages)
        
    #     context = {
    #         'suplier': sup_obj,
    #         'biils' : bills
    #     }
    #     return render(request,'suplier/supplier_details.html', context)



class CreateSuplierView(generic.CreateView):
    model = Supplier
    template_name = 'suplier/create_suplier.html'
    form_class = SupplierForm
    success_url = '/transaction/supliers_list'
    success_message = "the suplier created successfully"
    

class UpdateSuplierView(generic.UpdateView):
    model = Supplier
    template_name = 'suplier/update_suplier.html'
    form_class = SupplierForm
    success_url = '/transaction/supliers_list'
    success_message = "the suplier updated successfully"

class DeleteSuplierView(generic.View):
    def get(self,request,pk):
        suplier = get_object_or_404(Supplier , pk=pk)
        return render(request , 'suplier/delete_suplier.html' ,{'suplier':suplier})
    def post(self , request , pk):
        suplier = get_object_or_404(Supplier , pk=pk)
        suplier.is_deleted = True
        suplier.save()
        return redirect('supliers_list')
    

class PurchseListView(generic.ListView):
    model = PurchaseBill
    template_name = 'purchase/purchase_list.html'
    context_object_name = 'bills'
    ordering = ['-time']
    paginate_by = 10


class SelectSupplierView(generic.View):
    form_class = SelectSuplierForm
    template_name = 'purchase/select_supplier.html'

    def get(self ,request, *args , **kwargs):
        form = self.form_class
        return render(request , self.template_name , {'form':form})
    
    def post(self , request , *args , **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            supp_id = request.POST.get('suplier')
            supplier = get_object_or_404(Supplier , id=supp_id)
            return redirect('new_purchase' , supplier.id)
        return render(request , self.template_name , {'form':form})
    

class PurchaseCeateView(generic.View):
    template_name = 'purchase/new_purchase.html'

    def get(self,request ,pk ):
        formset = PurchaseItemFormset(request.GET or None)
        supp_id = get_object_or_404(Supplier , pk=pk)
        context = {
            'formset' : formset,
            'supp_id' : supp_id
        }
        return render(request , self.template_name , context)
    
    def post(self , request , pk):
        formset = PurchaseItemFormset(request.POST)
        supp_id = get_object_or_404(Supplier , pk=pk)
        if formset.is_valid():
            #create Bill
            bill_obj = PurchaseBill(suplier=supp_id)
            bill_obj.save()

            #create BillDetails
            bill_obj_details = PurchaseBillDetails(bill_no=bill_obj)
            bill_obj_details.save()
            for form in formset:
                bill_item = form.save(commit=False)
                bill_item.bill_no = bill_obj
                stock = get_object_or_404(InventoryStock , name=bill_item.stock.name)
                bill_item.total_price = bill_item.per_price * bill_item.quantity
                stock.quantity += bill_item.quantity
                stock.save()
                bill_item.save()
            messages.success(request , "Purchase Items have been registred succssfuly ")
            return redirect('purchase_bill', bill_no=bill_obj.bill_no)
            # return redirect('/')
        formset = PurchaseItemFormset(request.GET or None)
        context = {
            'formset' : formset,
            'supp_id' : supp_id
        }

        return render(request , self.template_name , context)

class PurchaseDeleteView(SuccessMessageMixin , generic.DeleteView):
    model = PurchaseBill
    template_name = 'purchase/delete_purchase.html'
    success_url = '/transaction/purchase_list'

    def post(self , *args , **kwargs):
        self.object = self.get_object()
        items = PurchaseItem.objects.filter(bill_no=self.object.bill_no)

        for item in items:
            stock = get_object_or_404(InventoryStock , name=item.stock.name)
            if stock.is_deleted == False:
                stock.quantity -= item.quantity
                stock.save()
        messages.success(self.request , "Purchase Bill Has Been Succssfuly Deleted")
        return super(PurchaseDeleteView, self).delete(*args , **kwargs)
    


class PurchaseBillView(generic.View):
    model = PurchaseBill
    template_name = 'bill/purchase_bill.html'
    bill_base = 'bill/bill_base.html'
    form_class = PurchaseDetailsForm

    def get_bill_context(self , bill_no ,form):
        bill = get_object_or_404(PurchaseBill , bill_no=bill_no)
        items = PurchaseItem.objects.filter(bill_no=bill_no)
        bill_details = get_object_or_404(PurchaseBillDetails , bill_no=bill_no)

        return {
            'bill':bill,
            'items':items,
            'bill_details':bill_details,
            'bill_base':self.bill_base,
            'form':form,
        }
    
    def get(self , request , bill_no):
        bill_details_obj = get_object_or_404(PurchaseBillDetails , bill_no=bill_no)
        form = self.form_class(instance=bill_details_obj)
        context = self.get_bill_context(bill_no=bill_no , form=form)
        return render(request , self.template_name , context)
    
    def post(self , request , bill_no):
        bill_details_obj = get_object_or_404(PurchaseBillDetails , bill_no=bill_no)
        form = self.form_class(request.POST , instance=bill_details_obj)

        if form.is_valid():
            form.save()
            messages.success(request , "Bill details have been successfuly modefied")
        else:
            messages.success(request , "There was an error updating the bill details")
        context = self.get_bill_context(bill_no , form)
        return render(request , self.template_name , context)
    

#Sales Section

class SaleCreateView(generic.View):
    template_name = "sales/sale_create.html"

    def get(self,request):
        form = SaleForm(request.GET or None)
        form_set = SaleItemFormset(request.GET or None)
        stocks = InventoryStock.objects.filter(is_deleted = False)

        context = {
            'form':form,
            'form_set':form_set,
            'stocks':stocks
        }
        return render(request , self.template_name , context)
    def post(self , request):
        form = SaleForm(request.POST)
        form_set = SaleItemFormset(request.POST)

        if form.is_vaid() and form_set.is_valid():
            bill_obj = form.save(commit=False)
            bill_obj.save()

            bill_detail_obj = SaleBillDetail(bill_no = bill_obj)
            bill_detail_obj.save()

            for form in form_set:
                bill_item = form.save(commit=False)
                bill_item.bill_no = bill_obj
                stock = get_object_or_404(InventoryStock , name=bill_item.stock.name )
                bill_item.total_price = bill_item.per_price * bill_item.quantity
                stock.quantity -= bill_item.quantity
                stock.save()
                bill_item.save()
            messages.success(request , "sold item has been registered successfully")
            return redirect('sale_bill' , bill_no = bill_obj.bill_no)
        form = SaleForm(request.GET or None)
        form_set = SaleItemFormset(request.GET or None)

        context = {
            'form':form,
            'form_set':form_set
        }

        return render(request , self.template_name , context)
    

class SaleListView(generic.ListView):
    model = SaleBill
    template_name = 'sales/sales_list.html'
    context_object_name = 'sale_bills'
    ordering = ['-time']
    paginate_by = 10



class SaleDeleteView(generic.DeleteView):
    model = SaleBill
    template_name = 'sales/sale_delete.html'
    redirect = 'transaction/sales'

    def post(self , *args , **kwargs):
        self.object = self.get_object()
        items = SaleItem.objects.filter(bill_no = self.object.bill_no)
        for item in items:
            stock =get_object_or_404(InventoryStock , name=item.stock.name)
            if stock.is_deleted == False:
                stock.quantity += item.quantity 
                stock.save()
        messages.success(self.request , "Sale Bill has been deleted successfully")
        return super(SaleDeleteView , self).delete(*args , **kwargs)
    

class SaleBillView(generic.View):
    model = SaleBill

src/transaction/templates/purchase/delete_purchase.html
{% extends "base.html" %}
{% block title %} Delete Purchase {% endblock title %}
{% block content %}
      <div class="row">
        <div class="col-md-12">
          <!-- messages here -->
          <div class="container">
            <!-- block content -->

                  
            <form method="post">
                {% csrf_token %}
              <fieldset class="form-group">
                  <div style="color:#575757; font-style: bold; font-size: 2rem; border-bottom: 1px solid white;">Delete Purchase Bill No {{object.bill_no}}</div> <br>
                  <h2 style="color:#575757;">Are you sure you want to delete the Purchase Bill No: {{object.bill_no}}?</h2>
              </fieldset>

              <div class="form-group">  
                  <button type="submit" class="btn btn-danger">Yes, Delete</button>
                  <a href="/" class="btn btn-secondary">Cancel</a>
              </div>
              
            </form>

        </div>
      </div>
     
{% endblock content %} 
 

src/transaction/templates/purchase/new_purchase.html
{% extends "base.html" %}
{% load static %}
{% block title %}New Purchase{% endblock title %}
{% block content %}
  <div class="row">

     <div class="col-md-12">
          <!-- messages here -->
          <div class="container">
            <!-- block content -->

            <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">New Purchase</div>

              <br>

              <div class="panel panel-default">
                <div class="panel-heading panel-heading-text">Supplier Details</div>
                <div class="panel-body">

                  <div class="form-group">
                    <label for="id_name" class="panel-body-text">Supplier Name:</label>
                    <input type="text" class="form-control textinput" id="id_name" value="{{supp_id.name}}" disabled>
                  </div>

                  <div class="form-row">
                    <div class="form-group col-md-6">
                      <label for="id_phone" class="panel-body-text">Phone No:</label>
                      <input type="text" class="form-control textinput" id="id_phone" value="{{supp_id.phone}}" disabled>
                    </div>
                    <div class="form-group col-md-6">
                      <label for="id_gstin" class="panel-body-text">GSTIN No:</label>
                      <input type="gstin" class="form-control textinput" id="id_gstin" value="{{supp_id.gstin}}" disabled>
                    </div>
                  </div>

                </div>
              </div>

              <br>

              <form method="post" class="panel panel-default">
                {% csrf_token %}
                {{ formset.management_form}}
                <div class="panel-heading panel-heading-text">Product Details</div>

                <div id="stockitem">
                  <div class="panel-body">
				
                    <div class="row form-row">
                    {% for form in formset %}
                      <div class="form-group col-md-6">
                        <label class="panel-body-text">Stock:</label>
                        {{form.stock }}
                      </div>
                      <div class="form-group col-md-2">
                        <label class="panel-body-text">Price per item:</label>
                        {{ form.per_price}}
                      </div>
                      <div class="form-group col-md-2">
                        <label class="panel-body-text">Quantity:</label>
                        {{ form.quantity }}
                      </div>
                      <div class="form-group col-md-1">
                        <label class="panel-body-text">Price:</label>
                        <input type="text" class="textinput form-control totalprice" value="1" disabled required>
                      </div>
                      <div class="form-group col-md-1">
                        <label class="panel-body-text" style="color: #000">.</label>
                        <button class="form-control btn btn-danger remove-form-row">-</button>
                      </div>
                    </div>
                    {% endfor %}
                    <div style="text-align: right;">
                      <a href="#" class="add-form-row">+ Add More</a>
                    </div>
                  </div>
                </div>


                <br>

                <div class="align-middle">
                  <button type="submit" class="btn btn-success">Add to Purchases</button>
                  <a href="#" class="btn btn-danger">Go Back</a>
                  <a href="#" class="btn btn-secondary">Cancel</a>
                </div>

              </form>

            </div>
        </div>
      </div>   
  </div> 
  <script type="text/javascript" src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/dialogbox.js' %}"></script>
  <script type="text/javascript">
    // Creates custom alert object
    var custom_alert = new custom_alert();

    // Stores the total number of item forms
    var total = 1;

    // Updates element index for dynamically added form rows
    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx;
        
        if ($(el).attr("for")) {
            $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        }
        if (el.id) {
            el.id = el.id.replace(id_regex, replacement);
        }
        if (el.name) {
            el.name = el.name.replace(id_regex, replacement);
        }
    }

    // Clones a form row to add a new one
    function cloneMore(selector, prefix) {
        var newElement = $(selector).clone(true);

        // Update input names and ids for the new element
        newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
            var name = $(this).attr('name');
            if (name) {
                name = name.replace('-' + (total - 1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            }
        });

        // Update labels for the new element
        newElement.find('label').each(function() {
            var forValue = $(this).attr('for');
            if (forValue) {
                forValue = forValue.replace('-' + (total - 1) + '-', '-' + total + '-');
                $(this).attr({'for': forValue});
            }
        });

        total++;
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);

        return false;
    }

    // Deletes a form row
    function deleteForm(prefix, btn) {
        if (total > 1) {
            btn.closest('.form-row').remove();

            var forms = $('.form-row');
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);

            // Update indices for remaining form rows
            for (var i = 0, formCount = forms.length; i < formCount; i++) {
                $(forms.get(i)).find(':input').each(function() {
                    updateElementIndex(this, prefix, i);
                });
            }

            total--;
        } else {
            custom_alert.render("Field cannot be deleted");
        }

        return false;
    }

    // Event listener to add a new form row
    $(document).on('click', '.add-form-row', function(e) {
        e.preventDefault();
        cloneMore('.form-row:last', 'form');
        return false;
    });

    // Event listener to remove a form row
    $(document).on('click', '.remove-form-row', function(e) {
        e.preventDefault();
        deleteForm('form', $(this));
        return false;
    });

    // Updates the total price by multiplying 'price per item' and 'quantity'
    $(document).on('change', '.setprice', function(e) {
        e.preventDefault();

        // Get the values
        var element = $(this);
        var quantity = element.parents('.form-row').find('.quantity').val();
        var perprice = element.parents('.form-row').find('.price').val();
        consol.log(quantity)
        consol.log(perprice)

        // Calculate the total
        var tprice = quantity * perprice;

        // Set the calculated total to the field
        element.parents('.form-row').find('.totalprice').val(tprice);

        return false;
    });
  </script>
{% endblock content %}

src/transaction/templates/purchase/purchase_list.html
{% extends "base.html" %}
{% block title %} Purchase List {% endblock title %}
{% block content %}

      <div class="row">
        <div class="col-md-12">
          <!-- messages here -->
          <div class="container">
            <!-- block content -->

            
            <div class="row" style="color: #575757; font-style: bold; font-size: 3rem;">
              <div class="col-md-8">Purchases List</div>
              <div class="col-md-4">               
                  <div style="float:right;"> <a class="btn btn-success" href="{% url 'select_supplier' %}">New Incoming Stock</a> </div>
              </div>
            </div>

            <br>

            <table class="table table-css table-hover table-bordered">

                <thead class="thead-dark align-middle">
                    <tr>
                        <th width="10%">Bill No.</th>
                        <th width="15%">Supplier</th>
                        <th width="15%">Stocks Purchased</th>
                        <th width="5%">Quantity Purchased</th>
                        <th width="15%">Total Purchased Price</th>
                        <th width="15%">Purchased Date</th>
                        <th width="25%">Actions</th>
                    </tr>
                </thead>
                {% if bills %}
                <tbody> 
                    {% for bill in bills %}        
                    <tr>
                        <td class="align-middle"> <p>{{bill.bill_no|truncatechars:10}}</p> </td>
                        <td class=""> 
                            <a href="{% url 'supplier_details' bill.suplier.id %}">{{bill.suplier.name}}</a> <br>
                            <small style="color: #909494">Ph No : {{bill.suplier.phone}} </small> 
                        </td>
                        <td class="align-middle">{% for item in bill.get_items_list  %}{{item.stock.name }}{% endfor %} <br></td>
                        <td class="align-middle">{% for item in bill.get_items_list  %}{{item.quantity}}{% endfor %}<br></td>     
                        <td class="align-middle">{{bill.get_total_price}}</td>
                        <td class="align-middle">{{bill.time.date}}</td>
                        <td class="align-middle"> <a href="{% url 'purchase_bill' bill.bill_no %}" class="btn btn-secondary btn-sm">View Bill</a> <a href="{% url 'delete_purchase' bill.bill_no %}" class="btn btn-danger btn-sm">Delete Bill</a> </td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>

            <div class="align-middle">
              {% if is_paginated %}
                  {% if page_obj.has_previous %}
                      <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                      <a class="btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
                  {% endif %}
              {% for n in page_obj.paginator.page_range %}
                  {% if page_obj.number == n %}
                      <a class="btn btn-info mb-4" href="?page={{n}}">{{n}}</a>
                  {% else %}
                      <a class="btn btn-outline-info mb-4" href="?page={{n}}">{{n}}</a>
                  {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
                  <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
                  <a class="btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages}}">Last</a>
              {% endif %}
          {% endif %}
          </div>
          {% else %}
          <br><br><br><br><br><br><br><br>
          <div style="color: #575757; font-style: bold; font-size: 1.5rem; text-align: center;">The records are empty.
            Please try
            adding some.</div>
            {% endif %}
        </div>
{% endblock content %}

src/transaction/templates/purchase/select_supplier.html
{% extends "base.html" %}
{% block title %}Select Supplier{% endblock title %}
{% block content %}
      <div class="row">
        <div class="col-md-12">
          <!-- messages here -->
          <div class="container">
            <!-- block content -->
            <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">Select Supplier</div> 
    
              <br>
              
              <form method="post">
                {% csrf_token %}
                      <div class="form-group">
                        {{ form }}
                      </div>

                  <br>
                  <div class="align-middle">
                      <button type="submit" class="btn btn-success">Next</button>
                      <a href="" class="btn btn-secondary">Cancel</a>
                  </div>
                  
              </form>

        </div>
      </div>
{% endblock content %}